// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SocketInfo.proto

package com.liubin.socket.pojo.proto;

public final class SocketInfo {
  private SocketInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SocketInfoFieldOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 day = 1;
    /**
     * <code>required int32 day = 1;</code>
     */
    boolean hasDay();
    /**
     * <code>required int32 day = 1;</code>
     */
    int getDay();
  }
  /**
   * Protobuf type {@code com.liubin.socket.pojo.proto.SocketInfoField}
   */
  public static final class SocketInfoField extends
      com.google.protobuf.GeneratedMessage
      implements SocketInfoFieldOrBuilder {
    // Use SocketInfoField.newBuilder() to construct.
    private SocketInfoField(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SocketInfoField(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SocketInfoField defaultInstance;
    public static SocketInfoField getDefaultInstance() {
      return defaultInstance;
    }

    public SocketInfoField getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SocketInfoField(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              day_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.liubin.socket.pojo.proto.SocketInfo.internal_static_com_liubin_socket_pojo_proto_SocketInfoField_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liubin.socket.pojo.proto.SocketInfo.internal_static_com_liubin_socket_pojo_proto_SocketInfoField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField.class, com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField.Builder.class);
    }

    public static com.google.protobuf.Parser<SocketInfoField> PARSER =
        new com.google.protobuf.AbstractParser<SocketInfoField>() {
      public SocketInfoField parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SocketInfoField(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SocketInfoField> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 day = 1;
    public static final int DAY_FIELD_NUMBER = 1;
    private int day_;
    /**
     * <code>required int32 day = 1;</code>
     */
    public boolean hasDay() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 day = 1;</code>
     */
    public int getDay() {
      return day_;
    }

    private void initFields() {
      day_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, day_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, day_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.liubin.socket.pojo.proto.SocketInfoField}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.liubin.socket.pojo.proto.SocketInfo.SocketInfoFieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.liubin.socket.pojo.proto.SocketInfo.internal_static_com_liubin_socket_pojo_proto_SocketInfoField_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.liubin.socket.pojo.proto.SocketInfo.internal_static_com_liubin_socket_pojo_proto_SocketInfoField_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField.class, com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField.Builder.class);
      }

      // Construct using com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        day_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.liubin.socket.pojo.proto.SocketInfo.internal_static_com_liubin_socket_pojo_proto_SocketInfoField_descriptor;
      }

      public com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField getDefaultInstanceForType() {
        return com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField.getDefaultInstance();
      }

      public com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField build() {
        com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField buildPartial() {
        com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField result = new com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.day_ = day_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField) {
          return mergeFrom((com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField other) {
        if (other == com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField.getDefaultInstance()) return this;
        if (other.hasDay()) {
          setDay(other.getDay());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDay()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.liubin.socket.pojo.proto.SocketInfo.SocketInfoField) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 day = 1;
      private int day_ ;
      /**
       * <code>required int32 day = 1;</code>
       */
      public boolean hasDay() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 day = 1;</code>
       */
      public int getDay() {
        return day_;
      }
      /**
       * <code>required int32 day = 1;</code>
       */
      public Builder setDay(int value) {
        bitField0_ |= 0x00000001;
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 day = 1;</code>
       */
      public Builder clearDay() {
        bitField0_ = (bitField0_ & ~0x00000001);
        day_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.liubin.socket.pojo.proto.SocketInfoField)
    }

    static {
      defaultInstance = new SocketInfoField(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.liubin.socket.pojo.proto.SocketInfoField)
  }

  public interface SocketInfoValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 openPrice = 1;
    /**
     * <code>required int32 openPrice = 1;</code>
     */
    boolean hasOpenPrice();
    /**
     * <code>required int32 openPrice = 1;</code>
     */
    int getOpenPrice();

    // required int32 lastClosePrice = 2;
    /**
     * <code>required int32 lastClosePrice = 2;</code>
     */
    boolean hasLastClosePrice();
    /**
     * <code>required int32 lastClosePrice = 2;</code>
     */
    int getLastClosePrice();

    // required int32 currentPrice = 3;
    /**
     * <code>required int32 currentPrice = 3;</code>
     */
    boolean hasCurrentPrice();
    /**
     * <code>required int32 currentPrice = 3;</code>
     */
    int getCurrentPrice();

    // required int32 todayMaxPrice = 4;
    /**
     * <code>required int32 todayMaxPrice = 4;</code>
     */
    boolean hasTodayMaxPrice();
    /**
     * <code>required int32 todayMaxPrice = 4;</code>
     */
    int getTodayMaxPrice();

    // required int32 todayMinPrice = 5;
    /**
     * <code>required int32 todayMinPrice = 5;</code>
     */
    boolean hasTodayMinPrice();
    /**
     * <code>required int32 todayMinPrice = 5;</code>
     */
    int getTodayMinPrice();

    // required int32 volume = 6;
    /**
     * <code>required int32 volume = 6;</code>
     */
    boolean hasVolume();
    /**
     * <code>required int32 volume = 6;</code>
     */
    int getVolume();

    // required int32 turnover = 7;
    /**
     * <code>required int32 turnover = 7;</code>
     */
    boolean hasTurnover();
    /**
     * <code>required int32 turnover = 7;</code>
     */
    int getTurnover();

    // optional int32 avgPrice5 = 8;
    /**
     * <code>optional int32 avgPrice5 = 8;</code>
     */
    boolean hasAvgPrice5();
    /**
     * <code>optional int32 avgPrice5 = 8;</code>
     */
    int getAvgPrice5();

    // optional int32 avgPrice10 = 9;
    /**
     * <code>optional int32 avgPrice10 = 9;</code>
     */
    boolean hasAvgPrice10();
    /**
     * <code>optional int32 avgPrice10 = 9;</code>
     */
    int getAvgPrice10();

    // optional int32 avgPrice20 = 10;
    /**
     * <code>optional int32 avgPrice20 = 10;</code>
     */
    boolean hasAvgPrice20();
    /**
     * <code>optional int32 avgPrice20 = 10;</code>
     */
    int getAvgPrice20();

    // optional int32 avgPrice30 = 11;
    /**
     * <code>optional int32 avgPrice30 = 11;</code>
     */
    boolean hasAvgPrice30();
    /**
     * <code>optional int32 avgPrice30 = 11;</code>
     */
    int getAvgPrice30();

    // optional int32 avgPrice60 = 12;
    /**
     * <code>optional int32 avgPrice60 = 12;</code>
     */
    boolean hasAvgPrice60();
    /**
     * <code>optional int32 avgPrice60 = 12;</code>
     */
    int getAvgPrice60();
  }
  /**
   * Protobuf type {@code com.liubin.socket.pojo.proto.SocketInfoValue}
   */
  public static final class SocketInfoValue extends
      com.google.protobuf.GeneratedMessage
      implements SocketInfoValueOrBuilder {
    // Use SocketInfoValue.newBuilder() to construct.
    private SocketInfoValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SocketInfoValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SocketInfoValue defaultInstance;
    public static SocketInfoValue getDefaultInstance() {
      return defaultInstance;
    }

    public SocketInfoValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SocketInfoValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              openPrice_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lastClosePrice_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              currentPrice_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              todayMaxPrice_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              todayMinPrice_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              volume_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              turnover_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              avgPrice5_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              avgPrice10_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              avgPrice20_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              avgPrice30_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              avgPrice60_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.liubin.socket.pojo.proto.SocketInfo.internal_static_com_liubin_socket_pojo_proto_SocketInfoValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liubin.socket.pojo.proto.SocketInfo.internal_static_com_liubin_socket_pojo_proto_SocketInfoValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue.class, com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue.Builder.class);
    }

    public static com.google.protobuf.Parser<SocketInfoValue> PARSER =
        new com.google.protobuf.AbstractParser<SocketInfoValue>() {
      public SocketInfoValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SocketInfoValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SocketInfoValue> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 openPrice = 1;
    public static final int OPENPRICE_FIELD_NUMBER = 1;
    private int openPrice_;
    /**
     * <code>required int32 openPrice = 1;</code>
     */
    public boolean hasOpenPrice() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 openPrice = 1;</code>
     */
    public int getOpenPrice() {
      return openPrice_;
    }

    // required int32 lastClosePrice = 2;
    public static final int LASTCLOSEPRICE_FIELD_NUMBER = 2;
    private int lastClosePrice_;
    /**
     * <code>required int32 lastClosePrice = 2;</code>
     */
    public boolean hasLastClosePrice() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 lastClosePrice = 2;</code>
     */
    public int getLastClosePrice() {
      return lastClosePrice_;
    }

    // required int32 currentPrice = 3;
    public static final int CURRENTPRICE_FIELD_NUMBER = 3;
    private int currentPrice_;
    /**
     * <code>required int32 currentPrice = 3;</code>
     */
    public boolean hasCurrentPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 currentPrice = 3;</code>
     */
    public int getCurrentPrice() {
      return currentPrice_;
    }

    // required int32 todayMaxPrice = 4;
    public static final int TODAYMAXPRICE_FIELD_NUMBER = 4;
    private int todayMaxPrice_;
    /**
     * <code>required int32 todayMaxPrice = 4;</code>
     */
    public boolean hasTodayMaxPrice() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 todayMaxPrice = 4;</code>
     */
    public int getTodayMaxPrice() {
      return todayMaxPrice_;
    }

    // required int32 todayMinPrice = 5;
    public static final int TODAYMINPRICE_FIELD_NUMBER = 5;
    private int todayMinPrice_;
    /**
     * <code>required int32 todayMinPrice = 5;</code>
     */
    public boolean hasTodayMinPrice() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 todayMinPrice = 5;</code>
     */
    public int getTodayMinPrice() {
      return todayMinPrice_;
    }

    // required int32 volume = 6;
    public static final int VOLUME_FIELD_NUMBER = 6;
    private int volume_;
    /**
     * <code>required int32 volume = 6;</code>
     */
    public boolean hasVolume() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 volume = 6;</code>
     */
    public int getVolume() {
      return volume_;
    }

    // required int32 turnover = 7;
    public static final int TURNOVER_FIELD_NUMBER = 7;
    private int turnover_;
    /**
     * <code>required int32 turnover = 7;</code>
     */
    public boolean hasTurnover() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 turnover = 7;</code>
     */
    public int getTurnover() {
      return turnover_;
    }

    // optional int32 avgPrice5 = 8;
    public static final int AVGPRICE5_FIELD_NUMBER = 8;
    private int avgPrice5_;
    /**
     * <code>optional int32 avgPrice5 = 8;</code>
     */
    public boolean hasAvgPrice5() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 avgPrice5 = 8;</code>
     */
    public int getAvgPrice5() {
      return avgPrice5_;
    }

    // optional int32 avgPrice10 = 9;
    public static final int AVGPRICE10_FIELD_NUMBER = 9;
    private int avgPrice10_;
    /**
     * <code>optional int32 avgPrice10 = 9;</code>
     */
    public boolean hasAvgPrice10() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 avgPrice10 = 9;</code>
     */
    public int getAvgPrice10() {
      return avgPrice10_;
    }

    // optional int32 avgPrice20 = 10;
    public static final int AVGPRICE20_FIELD_NUMBER = 10;
    private int avgPrice20_;
    /**
     * <code>optional int32 avgPrice20 = 10;</code>
     */
    public boolean hasAvgPrice20() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 avgPrice20 = 10;</code>
     */
    public int getAvgPrice20() {
      return avgPrice20_;
    }

    // optional int32 avgPrice30 = 11;
    public static final int AVGPRICE30_FIELD_NUMBER = 11;
    private int avgPrice30_;
    /**
     * <code>optional int32 avgPrice30 = 11;</code>
     */
    public boolean hasAvgPrice30() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 avgPrice30 = 11;</code>
     */
    public int getAvgPrice30() {
      return avgPrice30_;
    }

    // optional int32 avgPrice60 = 12;
    public static final int AVGPRICE60_FIELD_NUMBER = 12;
    private int avgPrice60_;
    /**
     * <code>optional int32 avgPrice60 = 12;</code>
     */
    public boolean hasAvgPrice60() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 avgPrice60 = 12;</code>
     */
    public int getAvgPrice60() {
      return avgPrice60_;
    }

    private void initFields() {
      openPrice_ = 0;
      lastClosePrice_ = 0;
      currentPrice_ = 0;
      todayMaxPrice_ = 0;
      todayMinPrice_ = 0;
      volume_ = 0;
      turnover_ = 0;
      avgPrice5_ = 0;
      avgPrice10_ = 0;
      avgPrice20_ = 0;
      avgPrice30_ = 0;
      avgPrice60_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOpenPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastClosePrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrentPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTodayMaxPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTodayMinPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVolume()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTurnover()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, openPrice_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, lastClosePrice_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, currentPrice_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, todayMaxPrice_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, todayMinPrice_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, volume_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, turnover_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, avgPrice5_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, avgPrice10_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, avgPrice20_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, avgPrice30_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, avgPrice60_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, openPrice_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lastClosePrice_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, currentPrice_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, todayMaxPrice_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, todayMinPrice_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, volume_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, turnover_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, avgPrice5_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, avgPrice10_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, avgPrice20_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, avgPrice30_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, avgPrice60_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.liubin.socket.pojo.proto.SocketInfoValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.liubin.socket.pojo.proto.SocketInfo.internal_static_com_liubin_socket_pojo_proto_SocketInfoValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.liubin.socket.pojo.proto.SocketInfo.internal_static_com_liubin_socket_pojo_proto_SocketInfoValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue.class, com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue.Builder.class);
      }

      // Construct using com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        openPrice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lastClosePrice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        currentPrice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        todayMaxPrice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        todayMinPrice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        volume_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        turnover_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        avgPrice5_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        avgPrice10_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        avgPrice20_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        avgPrice30_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        avgPrice60_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.liubin.socket.pojo.proto.SocketInfo.internal_static_com_liubin_socket_pojo_proto_SocketInfoValue_descriptor;
      }

      public com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue getDefaultInstanceForType() {
        return com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue.getDefaultInstance();
      }

      public com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue build() {
        com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue buildPartial() {
        com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue result = new com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.openPrice_ = openPrice_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastClosePrice_ = lastClosePrice_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.currentPrice_ = currentPrice_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.todayMaxPrice_ = todayMaxPrice_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.todayMinPrice_ = todayMinPrice_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.volume_ = volume_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.turnover_ = turnover_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.avgPrice5_ = avgPrice5_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.avgPrice10_ = avgPrice10_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.avgPrice20_ = avgPrice20_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.avgPrice30_ = avgPrice30_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.avgPrice60_ = avgPrice60_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue) {
          return mergeFrom((com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue other) {
        if (other == com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue.getDefaultInstance()) return this;
        if (other.hasOpenPrice()) {
          setOpenPrice(other.getOpenPrice());
        }
        if (other.hasLastClosePrice()) {
          setLastClosePrice(other.getLastClosePrice());
        }
        if (other.hasCurrentPrice()) {
          setCurrentPrice(other.getCurrentPrice());
        }
        if (other.hasTodayMaxPrice()) {
          setTodayMaxPrice(other.getTodayMaxPrice());
        }
        if (other.hasTodayMinPrice()) {
          setTodayMinPrice(other.getTodayMinPrice());
        }
        if (other.hasVolume()) {
          setVolume(other.getVolume());
        }
        if (other.hasTurnover()) {
          setTurnover(other.getTurnover());
        }
        if (other.hasAvgPrice5()) {
          setAvgPrice5(other.getAvgPrice5());
        }
        if (other.hasAvgPrice10()) {
          setAvgPrice10(other.getAvgPrice10());
        }
        if (other.hasAvgPrice20()) {
          setAvgPrice20(other.getAvgPrice20());
        }
        if (other.hasAvgPrice30()) {
          setAvgPrice30(other.getAvgPrice30());
        }
        if (other.hasAvgPrice60()) {
          setAvgPrice60(other.getAvgPrice60());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOpenPrice()) {
          
          return false;
        }
        if (!hasLastClosePrice()) {
          
          return false;
        }
        if (!hasCurrentPrice()) {
          
          return false;
        }
        if (!hasTodayMaxPrice()) {
          
          return false;
        }
        if (!hasTodayMinPrice()) {
          
          return false;
        }
        if (!hasVolume()) {
          
          return false;
        }
        if (!hasTurnover()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.liubin.socket.pojo.proto.SocketInfo.SocketInfoValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 openPrice = 1;
      private int openPrice_ ;
      /**
       * <code>required int32 openPrice = 1;</code>
       */
      public boolean hasOpenPrice() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 openPrice = 1;</code>
       */
      public int getOpenPrice() {
        return openPrice_;
      }
      /**
       * <code>required int32 openPrice = 1;</code>
       */
      public Builder setOpenPrice(int value) {
        bitField0_ |= 0x00000001;
        openPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 openPrice = 1;</code>
       */
      public Builder clearOpenPrice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        openPrice_ = 0;
        onChanged();
        return this;
      }

      // required int32 lastClosePrice = 2;
      private int lastClosePrice_ ;
      /**
       * <code>required int32 lastClosePrice = 2;</code>
       */
      public boolean hasLastClosePrice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 lastClosePrice = 2;</code>
       */
      public int getLastClosePrice() {
        return lastClosePrice_;
      }
      /**
       * <code>required int32 lastClosePrice = 2;</code>
       */
      public Builder setLastClosePrice(int value) {
        bitField0_ |= 0x00000002;
        lastClosePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lastClosePrice = 2;</code>
       */
      public Builder clearLastClosePrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastClosePrice_ = 0;
        onChanged();
        return this;
      }

      // required int32 currentPrice = 3;
      private int currentPrice_ ;
      /**
       * <code>required int32 currentPrice = 3;</code>
       */
      public boolean hasCurrentPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 currentPrice = 3;</code>
       */
      public int getCurrentPrice() {
        return currentPrice_;
      }
      /**
       * <code>required int32 currentPrice = 3;</code>
       */
      public Builder setCurrentPrice(int value) {
        bitField0_ |= 0x00000004;
        currentPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 currentPrice = 3;</code>
       */
      public Builder clearCurrentPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        currentPrice_ = 0;
        onChanged();
        return this;
      }

      // required int32 todayMaxPrice = 4;
      private int todayMaxPrice_ ;
      /**
       * <code>required int32 todayMaxPrice = 4;</code>
       */
      public boolean hasTodayMaxPrice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 todayMaxPrice = 4;</code>
       */
      public int getTodayMaxPrice() {
        return todayMaxPrice_;
      }
      /**
       * <code>required int32 todayMaxPrice = 4;</code>
       */
      public Builder setTodayMaxPrice(int value) {
        bitField0_ |= 0x00000008;
        todayMaxPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 todayMaxPrice = 4;</code>
       */
      public Builder clearTodayMaxPrice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        todayMaxPrice_ = 0;
        onChanged();
        return this;
      }

      // required int32 todayMinPrice = 5;
      private int todayMinPrice_ ;
      /**
       * <code>required int32 todayMinPrice = 5;</code>
       */
      public boolean hasTodayMinPrice() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 todayMinPrice = 5;</code>
       */
      public int getTodayMinPrice() {
        return todayMinPrice_;
      }
      /**
       * <code>required int32 todayMinPrice = 5;</code>
       */
      public Builder setTodayMinPrice(int value) {
        bitField0_ |= 0x00000010;
        todayMinPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 todayMinPrice = 5;</code>
       */
      public Builder clearTodayMinPrice() {
        bitField0_ = (bitField0_ & ~0x00000010);
        todayMinPrice_ = 0;
        onChanged();
        return this;
      }

      // required int32 volume = 6;
      private int volume_ ;
      /**
       * <code>required int32 volume = 6;</code>
       */
      public boolean hasVolume() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 volume = 6;</code>
       */
      public int getVolume() {
        return volume_;
      }
      /**
       * <code>required int32 volume = 6;</code>
       */
      public Builder setVolume(int value) {
        bitField0_ |= 0x00000020;
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 volume = 6;</code>
       */
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00000020);
        volume_ = 0;
        onChanged();
        return this;
      }

      // required int32 turnover = 7;
      private int turnover_ ;
      /**
       * <code>required int32 turnover = 7;</code>
       */
      public boolean hasTurnover() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 turnover = 7;</code>
       */
      public int getTurnover() {
        return turnover_;
      }
      /**
       * <code>required int32 turnover = 7;</code>
       */
      public Builder setTurnover(int value) {
        bitField0_ |= 0x00000040;
        turnover_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 turnover = 7;</code>
       */
      public Builder clearTurnover() {
        bitField0_ = (bitField0_ & ~0x00000040);
        turnover_ = 0;
        onChanged();
        return this;
      }

      // optional int32 avgPrice5 = 8;
      private int avgPrice5_ ;
      /**
       * <code>optional int32 avgPrice5 = 8;</code>
       */
      public boolean hasAvgPrice5() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 avgPrice5 = 8;</code>
       */
      public int getAvgPrice5() {
        return avgPrice5_;
      }
      /**
       * <code>optional int32 avgPrice5 = 8;</code>
       */
      public Builder setAvgPrice5(int value) {
        bitField0_ |= 0x00000080;
        avgPrice5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 avgPrice5 = 8;</code>
       */
      public Builder clearAvgPrice5() {
        bitField0_ = (bitField0_ & ~0x00000080);
        avgPrice5_ = 0;
        onChanged();
        return this;
      }

      // optional int32 avgPrice10 = 9;
      private int avgPrice10_ ;
      /**
       * <code>optional int32 avgPrice10 = 9;</code>
       */
      public boolean hasAvgPrice10() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 avgPrice10 = 9;</code>
       */
      public int getAvgPrice10() {
        return avgPrice10_;
      }
      /**
       * <code>optional int32 avgPrice10 = 9;</code>
       */
      public Builder setAvgPrice10(int value) {
        bitField0_ |= 0x00000100;
        avgPrice10_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 avgPrice10 = 9;</code>
       */
      public Builder clearAvgPrice10() {
        bitField0_ = (bitField0_ & ~0x00000100);
        avgPrice10_ = 0;
        onChanged();
        return this;
      }

      // optional int32 avgPrice20 = 10;
      private int avgPrice20_ ;
      /**
       * <code>optional int32 avgPrice20 = 10;</code>
       */
      public boolean hasAvgPrice20() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 avgPrice20 = 10;</code>
       */
      public int getAvgPrice20() {
        return avgPrice20_;
      }
      /**
       * <code>optional int32 avgPrice20 = 10;</code>
       */
      public Builder setAvgPrice20(int value) {
        bitField0_ |= 0x00000200;
        avgPrice20_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 avgPrice20 = 10;</code>
       */
      public Builder clearAvgPrice20() {
        bitField0_ = (bitField0_ & ~0x00000200);
        avgPrice20_ = 0;
        onChanged();
        return this;
      }

      // optional int32 avgPrice30 = 11;
      private int avgPrice30_ ;
      /**
       * <code>optional int32 avgPrice30 = 11;</code>
       */
      public boolean hasAvgPrice30() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 avgPrice30 = 11;</code>
       */
      public int getAvgPrice30() {
        return avgPrice30_;
      }
      /**
       * <code>optional int32 avgPrice30 = 11;</code>
       */
      public Builder setAvgPrice30(int value) {
        bitField0_ |= 0x00000400;
        avgPrice30_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 avgPrice30 = 11;</code>
       */
      public Builder clearAvgPrice30() {
        bitField0_ = (bitField0_ & ~0x00000400);
        avgPrice30_ = 0;
        onChanged();
        return this;
      }

      // optional int32 avgPrice60 = 12;
      private int avgPrice60_ ;
      /**
       * <code>optional int32 avgPrice60 = 12;</code>
       */
      public boolean hasAvgPrice60() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 avgPrice60 = 12;</code>
       */
      public int getAvgPrice60() {
        return avgPrice60_;
      }
      /**
       * <code>optional int32 avgPrice60 = 12;</code>
       */
      public Builder setAvgPrice60(int value) {
        bitField0_ |= 0x00000800;
        avgPrice60_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 avgPrice60 = 12;</code>
       */
      public Builder clearAvgPrice60() {
        bitField0_ = (bitField0_ & ~0x00000800);
        avgPrice60_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.liubin.socket.pojo.proto.SocketInfoValue)
    }

    static {
      defaultInstance = new SocketInfoValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.liubin.socket.pojo.proto.SocketInfoValue)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liubin_socket_pojo_proto_SocketInfoField_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_liubin_socket_pojo_proto_SocketInfoField_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_liubin_socket_pojo_proto_SocketInfoValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_liubin_socket_pojo_proto_SocketInfoValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020SocketInfo.proto\022\034com.liubin.socket.po" +
      "jo.proto\"\036\n\017SocketInfoField\022\013\n\003day\030\001 \002(\005" +
      "\"\205\002\n\017SocketInfoValue\022\021\n\topenPrice\030\001 \002(\005\022" +
      "\026\n\016lastClosePrice\030\002 \002(\005\022\024\n\014currentPrice\030" +
      "\003 \002(\005\022\025\n\rtodayMaxPrice\030\004 \002(\005\022\025\n\rtodayMin" +
      "Price\030\005 \002(\005\022\016\n\006volume\030\006 \002(\005\022\020\n\010turnover\030" +
      "\007 \002(\005\022\021\n\tavgPrice5\030\010 \001(\005\022\022\n\navgPrice10\030\t" +
      " \001(\005\022\022\n\navgPrice20\030\n \001(\005\022\022\n\navgPrice30\030\013" +
      " \001(\005\022\022\n\navgPrice60\030\014 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_liubin_socket_pojo_proto_SocketInfoField_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_liubin_socket_pojo_proto_SocketInfoField_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_liubin_socket_pojo_proto_SocketInfoField_descriptor,
              new java.lang.String[] { "Day", });
          internal_static_com_liubin_socket_pojo_proto_SocketInfoValue_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_liubin_socket_pojo_proto_SocketInfoValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_liubin_socket_pojo_proto_SocketInfoValue_descriptor,
              new java.lang.String[] { "OpenPrice", "LastClosePrice", "CurrentPrice", "TodayMaxPrice", "TodayMinPrice", "Volume", "Turnover", "AvgPrice5", "AvgPrice10", "AvgPrice20", "AvgPrice30", "AvgPrice60", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
